name: Strava Auto Post

on:
  repository_dispatch:
    types: [strava_activity]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate post
        run: node scripts/strava_to_post.js '${{ toJson(github.event.client_payload) }}'

      - name: Commit files
        run: |
          git config user.name "claudiostoduto"
          git config user.email "actions@github.com"
          git add .
          git commit -m "New Strava activity" || echo "Nothing to commit"
          git push
